website/auth.py
from flask import Blueprint, flash, render_template, request, url_for, redirect
from werkzeug.security import generate_password_hash, check_password_hash

# from .models import User
from website.forms import LoginForm, User_RegisterationForm
from flask_login import login_user, login_required, logout_user
from . import db
from .models import *
from sqlalchemy import desc

# create a blueprint
bp = Blueprint("auth", __name__)


# LOGIN USER
@bp.route("/login", methods=["GET", "POST"])
def login():  # view function
    print("In Login View function")
    login_form = LoginForm()
    error = None
    if login_form.validate_on_submit() == True:
        email = login_form.email.data
        password = login_form.password.data
        user = db.session.scalar(db.select(User).where(User.email == email))
        if user is None:
            error = "Incorrect credentials supplied"
        elif not check_password_hash(
            user.password_hash, password
        ):  # takes the hash and password
            error = "Incorrect credentials supplied"
        if error is None:
            login_user(user)
            return redirect(url_for("main.index"))
        else:
            flash(error)
    return render_template("user.html", form=login_form)


# REGISTER USER
@bp.route("/register", methods=["GET", "POST"])
def register():
    reg_form = User_RegisterationForm()
    error = None
    if reg_form.validate_on_submit() == True:
        fname = reg_form.fname.data
        lname = reg_form.lname.data
        phonenum = reg_form.phonenum.data
        email = reg_form.email.data
        password = reg_form.password.data
        prevUser = db.session.scalar(db.select(User).where(User.email == email))
        if prevUser:
            error = "This email is already taken. Please use another."
            flash(error)
            return render_template("register.html", form=reg_form, error=error)
        if error is None:
            # form location
            location = Location(
                street=reg_form.street.data,
                suburb=reg_form.suburb.data,
                city=reg_form.city.data,
                postcode=reg_form.postcode.data,
                state=reg_form.state.data,
            )
            db.session.add(location)
            db.session.commit()
            get_location = (
                db.session.query(Location).order_by(desc(Location.id)).first()
            )

            pwd_hash = generate_password_hash(password)
            newUser = User(
                fname=fname,
                lname=lname,
                email=email,
                password_hash=pwd_hash,
                phonenum=phonenum,
                location_id=get_location.id,
            )
            db.session.add(newUser)
            db.session.commit()
            flash("You have successfully registered an account. Please login below.")
            return redirect(url_for("auth.login"))
        else:
            flash(error)
    else:
        return render_template("register.html", form=reg_form, error=error)


# LOGOUT USER
@bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, abort
from flask_login import current_user
from .models import *
from .event_funcs import get_filtered_events

bp = Blueprint("main", __name__)


@bp.route("/")
def index():
    check_event_status()
    filter = None

    # clear previous search arguments
    request_args = request.args.to_dict()
    request_args.pop("search", None)

    # show all events (not logged in)
    if current_user.is_authenticated:
        events = get_filtered_events(current_user)

    # show events user has not created or registered in
    else:
        events = db.session.query(Event).filter(Event.status_id == 1).all()

    count = len(events)
    return render_template("index.html", events=events, filter=filter, count=count)


def check_event_status():
    current_date = datetime.now()
    # events become inactive on the day of (don't accept late registrations)
    events = db.session.query(Event).filter(Event.date <= current_date).all()
    for event in events:
        if event.status != 3:
            event.status_id = 3  # inactive event (in the past)
            print(f"Updating event {event} with new status INACTIVE")
            db.session.commit()


# event title based search
@bp.route("/search")
def search():
    search_query = request.args.get("search", "")
    if search_query:
        query = "%" + search_query + "%"
        events = db.session.query(Event).filter(Event.title.like(query)).all()
        count = len(events)
        return render_template(
            "index.html", events=events, search=True, query=search_query, count=count
        )
    else:
        return redirect(url_for("main.index"))


# sort by
@bp.route("/sort-by/<string:sort>")
def sort_by(sort):
    valid_sorts = ["date", "causes", "availability"]
    if sort not in valid_sorts:
        abort(401)

    if sort == "date":
        events = (
            db.session.query(Event)
            .filter(Event.status_id == 1)
            .order_by(Event.date)
            .all()
        )
        filter = "date"

    elif sort == "causes":
        events = (
            db.session.query(Event)
            .filter(Event.status_id == 1)
            .order_by(Event.genre_id)
            .all()
        )
        filter = "causes"

    elif sort == "availability":
        events = db.session.query(Event).order_by(Event.status_id).all()
        filter = "availability"

    count = len(events)
    return render_template("index.html", events=events, filter=filter, count=count)


# filter by state
@bp.route("/filter-state/<string:state>")
def filter_state(state):
    valid_states = ["QLD", "NSW", "TAS", "VIC", "WA", "SA", "ACT", "NT"]
    if state not in valid_states:
        abort(404)

    events = (
        db.session.query(Event)
        .filter(Event.status_id == 1)
        .join(Location)
        .filter(Location.state == state)
        .all()
    )
    filter = state
    count = len(events)
    return render_template("index.html", events=events, filter=filter, count=count)


# filter by cause
@bp.route("/filter-cause/<int:cause>")
def filter_cause(cause):
    if cause < 1 or cause > 8:
        abort(404)

    events = (
        db.session.query(Event)
        .filter(Event.status_id == 1)
        .filter(Event.genre_id == cause)
        .all()
    )

    genre = db.session.query(EventGenre.title).filter(EventGenre.id == cause).first()

    filter = genre[0]
    count = len(events)
    return render_template("index.html", events=events, filter=filter, count=count)

website/templates/base.html
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <link id="dark-theme-icon" rel="icon" href="{{ url_for('static', filename='img/favicon_light.png') }}" />
  <link id="light-theme-icon" rel="icon" href="{{ url_for('static', filename='img/logo.png') }}" />

  <title>Changemakers</title>
  <link href="{{ url_for('static',filename='style/style.css') }}" rel="stylesheet" type="text/css" />

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Sigmar&display=swap"
    rel="stylesheet" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.18.0/font/bootstrap-icons.css" />
</head>

<body>
  <!--=========================================================================================-->
  <!--==== HEADER =============================================================================-->
  <!--=========================================================================================-->
  <header>
    <!--=========================================================================================-->
    <!--==== NAVBAR =============================================================================-->
    <!--=========================================================================================-->

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img src="{{ url_for('static', filename='img/logo.png') }}" alt="Logo"
            class="logo d-inline-block align-text-top img-fluid" />
          <span class="nav-name">Changemakers</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportContent"
          aria-controls="navbarSupportContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            {% if current_user.is_authenticated %}
            <div class="navbar-nav me-auto w-100">
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('event.created_events') }}">My Events</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('event.create') }}">Create an Event</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
              </li>
            </div>
            <div class="w-100 justify-content-end align-content-center d-grid px-4">
              <a class="nav-link disabled text-muted welcome w-100 h-auto d-block" href="#">Welcome Back
                {{current_user.fname}}!</a>
            </div>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
            </li>
            {% endif %}
          </ul>
          <form class="d-flex pt-3" action="{{url_for('main.search')}}">
            <input type="text" name="search" class="form-control flex-grow-1 my-1 mr-sm-2" id="SearchForm"
              placeholder="Search">
          </form>
        </div>
      </div>
    </nav>

    {% block header %} {% endblock %}
  </header>

  {% block content %} {% endblock %}
</body>

<!--=========================================================================================-->
<!--==== Footer =============================================================================-->
<!--=========================================================================================-->

<footer class="container-fluid p-4">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
      <div class="col mb-3">
        <a href="{{ url_for('main.index') }}"
          class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none">
          <div class="container text-center">
            <img class="logo" src="{{url_for('static', filename='img/logo.png')}}" alt="" />
          </div>
        </a>
        <a class="fs-2 text-decoration-none text-reset" href="/">Changemakers</a>
        <p><i>Changing the way people volunteer.</i></p>
        <ul class="nav gap-3">
          <li>
            <a href="#"><img src="./static/img/icons/instagram.svg" alt="" /></a>
          </li>
          <li>
            <a href="#"><img src="./static/img/icons/twitter.svg" alt="" /></a>
          </li>
          <li>
            <a href="#"><img src="./static/img/icons/facebook.svg" alt="" /></a>
          </li>
        </ul>
        <p class="text-body-secondary mt-4">Copyright &copy; 2023. Changemakers, all rights reserved</p>
      </div>

      <div class="col mb-3"></div>

      <div class="col mb-3">
        <h5>Contact Us</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Email:
              changemakers@change.com</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Phone: +61 456-7890</a></li>
          <br />
          <h5>Follow Us:</h5>
          <li class="nav-item mb-2"><a href="https://www.tiktok.com/" class="nav-link p-0 text-body-secondary">TikTok</a></li>
          <li class="nav-item mb-2"><a href="https://www.instagram.com/" class="nav-link p-0 text-body-secondary">Instagram</a></li>
          <li class="nav-item mb-2"><a href="https://www.facebook.com/" class="nav-link p-0 text-body-secondary">Facebook</a></li>
          <li class="nav-item mb-2"><a href="https://www.twitter.com/" class="nav-link p-0 text-body-secondary">Twitter</a></li>
        </ul>
      </div>

      <div class="col mb-3">
        <h5>Explore</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="{{ url_for('main.index') }}"
              class="nav-link p-0 text-body-secondary">Home</a></li>
          <li class="nav-item mb-2"><a href="{{ url_for('main.index') }}"
              class="nav-link p-0 text-body-secondary">Events</a></li>
          <li class="nav-item mb-2"><a href="{{ url_for('event.create') }}"
              class="nav-link p-0 text-body-secondary">Create Event</a></li>
          <li class="nav-item mb-2"><a href="{{ url_for('event.created_events') }}" class="nav-link p-0 text-body-secondary">My
              Events</a></li>
          <li class="nav-item mb-2"><a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=PL8dZXjD8meS_WZzEKSReIBPLzKaW3HboH&index=2" class="nav-link p-0 text-body-secondary">About
              Us</a></li>
        </ul>
      </div>

      <div class="col mb-3">
        <h5>Legal</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="/terms" class="nav-link p-0 text-body-secondary">Terms of Service</a></li>
          <li class="nav-item mb-2"><a href="/privacy" class="nav-link p-0 text-body-secondary">Privacy Policy</a></li>
          <li class="nav-item mb-2"><a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=PL8dZXjD8meS_WZzEKSReIBPLzKaW3HboH&index=2" class="nav-link p-0 text-body-secondary">Cookie Policy</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

<!--=========================================================================================-->
<!--==== SCRIPTS =============================================================================-->
<!--=========================================================================================-->

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
  integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
  integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
<script src="{{ url_for('static', filename='javascript/script.js') }}"></script>

</html>

website/templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="in-between">
  <div class="p-5 mb-4 bg-light jumbotronback">
    <div class="container-xl py-5">
      <h1 class="display-1 fw-bold text-light jumbo-text">Changemakers</h1>
      <p class="col-md-8 fs-3 text-light jumbo-text">
        You can make a difference. <span class="impact">Volunteer</span> for an event near you today.
      </p>
      {% if current_user.is_authenticated %}
      <a href="{{ url_for('main.index') }}" class="btn button w-25">Join in Now</a>
      {% else %}
      <a href="{{ url_for('auth.login') }}" class="btn button w-25">Join in Now</a>
      {% endif %}
    </div>
  </div>

  <nav class="navbar navbar-expand-lg filter-nav nav-justified flex-rowjustify-content-around" style="margin-top: -2%">
    <div class="container">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <button class="btn dropdown-toggle filter-toggle" type="button" id="dropdownMenu3" data-bs-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Sort Results By
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu3" style="position: absolute">
            <a class="dropdown-item" href="{{ url_for('main.sort_by', sort='date') }}">Coming Up Soon</a>
            <a class="dropdown-item" href="{{ url_for('main.sort_by', sort='causes') }}">Causes</a>
            <a class="dropdown-item" href="{{ url_for('main.sort_by', sort='availability') }}">All Availability</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <button class="btn dropdown-toggle filter-toggle" type="button" id="dropdownMenu1" data-bs-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Causes
          </button>
          <div class="dropdown-menu p-3" aria-labelledby="dropdownMenu1" style="position: absolute">
            <a class="dropdown-item" href="{{ url_for('main.filter_cause', cause='1') }}"><img
                src="{{ url_for('static', filename='/img/advocacy.png') }}" class="volunteer-type-img" />Advocacy</a>
            <a class="dropdown-item" href="{{ url_for('main.filter_cause', cause='2') }}"><img
                src="{{ url_for('static', filename='/img/animals.png') }}" class="volunteer-type-img" />Animals</a>
            <a class="dropdown-item" href="{{ url_for('main.filter_cause', cause='3') }}"><img
                src="{{ url_for('static', filename='/img/companionship.png') }}"
                class="volunteer-type-img" />Companionship</a>
            <a class="dropdown-item" href="{{ url_for('main.filter_cause', cause='4') }}"><img
                src="{{ url_for('static', filename='/img/disaster.png') }}" class="volunteer-type-img" />Disaster
              Relief</a>
            <a class="dropdown-item" href="{{ url_for('main.filter_cause', cause='5') }}"><img
                src="{{ url_for('static', filename='/img/elderly.png') }}" class="volunteer-type-img" />Elderly</a>
            <a class="dropdown-item" href="{{ url_for('main.filter_cause', cause='6') }}"><img
                src="{{ url_for('static', filename='/img/environment.png') }}"
                class="volunteer-type-img" />Environment</a>
            <a class="dropdown-item" href="{{ url_for('main.filter_cause', cause='7') }}"><img
                src="{{ url_for('static', filename='/img/food.png') }}" class="volunteer-type-img" />Food and Water</a>
            <a class="dropdown-item" href="{{ url_for('main.filter_cause', cause='8') }}"><img
                src="{{ url_for('static', filename='/img/teaching.png') }}" class="volunteer-type-img" />Teaching and
              Learning</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <button class="btn dropdown-toggle filter-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Location
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2" style="position: absolute">
            <a href="{{ url_for('main.filter_state', state='QLD') }}" class="dropdown-item" type="button">QLD</a>
            <a href="{{ url_for('main.filter_state', state='NSW') }}" class="dropdown-item" type="button">NSW</a>
            <a href="{{ url_for('main.filter_state', state='TAS') }}" class="dropdown-item" type="button">TAS</a>
            <a href="{{ url_for('main.filter_state', state='VIC') }}" class="dropdown-item" type="button">VIC</a>
            <a href="{{ url_for('main.filter_state', state='WA') }}" class="dropdown-item" type="button">WA</a>
            <a href="{{ url_for('main.filter_state', state='SA') }}" class="dropdown-item" type="button">SA</a>
            <a href="{{ url_for('main.filter_state', state='ACT') }}" class="dropdown-item" type="button">ACT</a>
            <a href="{{ url_for('main.filter_state', state='NT') }}" class="dropdown-item" type="button">NT</a>
          </div>
        </li>
      </ul>

    </div>
  </nav>
</div>

</br>

{% if search == True %}
<h1 class="sub-title">Search Results For "{{query}}"</h1>
{% elif filter %}
<h1 class="sub-title">Showing Events Filtered by "{{filter}}"</h1>
{% else %}
<h1 class="sub-title">Upcoming Volunteer Opportunities For You</h1>
{% endif %}

<div class="horizontal-divider"></div>

{% if not events %}
<div class="container text-center">
  <img src="{{ url_for('static', filename='/img/empty.svg') }}" alt="" style="max-width: 400px">
  <p>No events found.</p>
</div>
{% else %}
<div class="container">
  <div class="card-group">
    <div class="row">
      {% for event in events %}
      <div class="card col-lg-3 col-md-6 col-sm-12 info-card bg-light" style="min-width: 300px">
        <img class="card-img-top card-img event-img-card" src="/{{event.image}}" alt="Card image cap" />
        <div class="ribbon">
          <p>Status: <span class="
            {% if event.status_id == 1%}open
            {% elif event.status_id == 2%}closed
            {% elif event.status_id == 3%}inactive
            {% elif event.status_id == 4%}cancelled
            {% endif %}
            ">{{ event.status.status }}</span></p>
        </div>
        <div class="card-body">
          <h5 class="card-title card-tit">
            {% if event.genre_id == 1 %}
            <img src="{{ url_for('static', filename='img/advocacy.png') }}" class="volunteer-type-img" />
            {% elif event.genre_id == 2 %}
            <img src="{{ url_for('static', filename='img/animals.png') }}" class="volunteer-type-img" />
            {% elif event.genre_id == 3 %}
            <img src="{{ url_for('static', filename='img/companionship.png') }}" class="volunteer-type-img" />
            {% elif event.genre_id == 4 %}
            <img src="{{ url_for('static', filename='img/disaster.png') }}" class="volunteer-type-img" />
            {% elif event.genre_id == 5 %}
            <img src="{{ url_for('static', filename='img/elderly.png') }}" class="volunteer-type-img" />
            {% elif event.genre_id == 6 %}
            <img src="{{ url_for('static', filename='img/environment.png') }}" class="volunteer-type-img" />
            {% elif event.genre_id == 7 %}
            <img src="{{ url_for('static', filename='img/food.png') }}" class="volunteer-type-img" />
            {% elif event.genre_id == 8 %}
            <img src="{{ url_for('static', filename='img/teaching.png') }}" class="volunteer-type-img" />
            {% endif %}
            <a href="{{ url_for('event.show', id=event.id) }}">{{ event.title }}</a>
          </h5>

          <h6 class="card-subtitle mb-2 location">
            <img class="pin-drop" src="{{url_for('static', filename='/img/pin.png')}}" alt="Pin drop" /><u>{{
              event.location.suburb }}, {{ event.location.state }}</u> | {{ event.date.strftime("%d/%m/%Y") }}
          </h6>

          <div class="horizontal-divider"></div>

          {% if current_user.is_authenticated and event.user_id == current_user.id %}
          <a href=" {{ url_for('event.show', id=event.id) }}" class="btn button-2">View My Event</a>
          {% else %}
          <a href=" {{ url_for('event.show', id=event.id) }}" class="btn button-2">Volunteer Now</a>
          {% endif %}
        </div>
      </div>

      {% endfor %}
      {% endif %}




    </div>
  </div>
</div>
</br>
<div class="container text-center">
  <i>{{count}} results returned.</i>
</div>
</br>
{% endblock %}

website/templates/register.html
{% extends 'base.html' %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}
<div class="login-reg-container">
    <h1>Register</h1>

    <!-- flashes any messages to the user -->
    {% with messages = get_flashed_messages() %}
    {% if messages %} <!-- check if there are any messages -->
    <div class="container-fluid">
        <div class="row mt-3 mb-3">
            <div class="col-md-12">
                {% for message in messages %} <!--loop through the messages-->
                <div class="alert alert-info">{{message}}</div> <!--display as alert-->
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
    {% endwith %}

    <div class="col-md-6 ml-5">
        {{render_form(form)}}
        <p>
            Already have an account with us?
            <a href="{{ url_for('auth.login') }}" class="links">
                Login here.
            </a>
        </p>
    </div>
</div>
{% endblock %}

website/templates/user.html
{% extends "base.html" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}
<div class="login-reg-container">
    <h1>Login</h1>

    <!-- flashes any messages to the user -->
    {% with messages = get_flashed_messages() %}
    {% if messages %} <!-- check if there are any messages -->
    <div class="container-fluid">
        <div class="row mt-3 mb-3">
            <div class="col-md-12">
                {% for message in messages %} <!--loop through the messages-->
                <div class="alert alert-info">{{message}}</div> <!--display as alert-->
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
    {% endwith %}

    <div class="col-md-6 ml-5">
        {{render_form(form)}}

        <p>
            Don't have an account with us?
            <a class="links" href="{{ url_for('auth.register') }}">
                Register here.
            </a>
        </p>
    </div>

</div>
{% endblock %}